version: '3.1'

services:
  mysql:
    container_name: 'mysql-image'
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=eco_market
      - MYSQL_USER=eco_user
      - MYSQL_PASSWORD=12345678
    ports:
      - "65050:3306"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    ports:
      - "8808:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/eco_market
      - SPRING_DATASOURCE_USERNAME=eco_user
      - SPRING_DATASOURCE_PASSWORD=12345678

volumes:
  pg_eco_market: